### ISSUE TITLE
minify 1.3.59 seems to break codemirror latest

### ISSUE THREAD

**Issue by jonnybradley** [matthiasmullie/minify#242]
Hi,

We just encountered a failure with v1.3.59 but it's ok on v1.3.58.

It seems to remove a space from [this regular expression](https://github.com/codemirror/CodeMirror/blob/master/mode/markdown/markdown.js#L90) resulting in an invalid pattern. The previous version seems fine with it.

The original pattern is
    `/^ *(?:\={1,}|-{1,})\s*$/`
and this becomes
    `/^*(?:\={1,}|-{1,})\s*$/`

Hope it's an easy one, thanks in advance!

**Comment by matthiasmullie** [comment]
Hi @jonnybradley 

That regex by itself seems to work fine, but I found it was not properly detecting some of the other regexes in your code, which may have caused it to incorrectly safeguard some of the rest of your code from whitespace stripping.
I just pushed a new commit - can you test if this works for you now?

Thanks!

**Comment by jonnybradley** [comment]
Hi @matthiasmullie 

Thanks for the speedy commit, but i fear it didn't fix our issue. I'm now on dev-master 2e54f84 locally, so up to date i think... but i still get `/^ *(?:\={1,}|-{1,})\s*$/` turning into `/^*(?:\={1,}|-{1,})\s*$/` and Firefox reports _"SyntaxError: nothing to repeat"_

Hmm, actually, i think i must be in the wrong place, that last commit on master here (2e54f84) was 11 days ago apparently, should i be looking somewhere else? Ok, seems that the 11 day ago commit is listed after the 2 days ago one (!?) and on matthiasmullie/minify/src/JS.php:267 i have the same fix as in 473896b so i think i'm looking at the same thing... and still have the same bug, sorry :(

TIA

**Comment by matthiasmullie** [comment]
Hey @jonnybradley 

I just minified the entire file with the latest Minify release, and that regex minified just fine for me now.
Can you try upgrading to latest release?

If you still experience this problem, try increasing pcre.backtrack_limit & pcre.recursion_limit (http://php.net/manual/en/pcre.configuration.php)?
If they're too low & the minify file too complex, that could cause the processing to fail.

If the problem persists, feel free to reopen this ticket with some additional details (complete JS, PHP version, pcre config, ...)

**Comment by jonnybradley** [comment]
Hi @matthiasmullie 

Good suggestion to try the pcre limits, but sadly increasing them made no difference (up to 100 times the defaults, 1000 times made apache most unhappy). I also put in a breakpoint testing for preg_last_error() in case there was a clue in there, but no joy :(

The only fix was to revert to 1.3.58 (i re-tried 1.3.59 again just in case, but that's also definitely broken for us, as initially reported).

Most mysterious... but thanks for trying!
